# Generated by Django 3.1.1 on 2020-09-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidlstatsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdatamodel',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
    ]
