# Generated by Django 3.1.1 on 2020-10-13 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidlstatsApp', '0003_auto_20200924_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoppig_id', models.IntegerField()),
                ('date_of_shoppings',models.DateField(default=datetime.date.today)),
                ('total_cost', models.FloatField(default=0.0)),
                ('vat_a', models.FloatField(default=0.0)),
                ('vat_b', models.FloatField(default=0.0)),
                ('vat_c', models.FloatField(default=0.0)),
                ('max_price', models.FloatField(default=0.0)),
                ('min_price', models.FloatField(default=0.0)),
                ('median_cost', models.FloatField(default=0.0)),
                ('mean_cost', models.FloatField(default=0.0)),
            ],
        ),

    ]
