# Generated by Django 3.1.1 on 2020-10-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidlstatsApp', '0004_auto_20201014_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rcp')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
